import PDFDocument from 'pdfkit';
import { Response } from 'express';

interface PdfOptions {
  title: string;
  subtitle?: string;
  author?: string;
  watermark?: string;
}

export function createPdfDocument(options: PdfOptions): PDFKit.PDFDocument {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 50,
    info: {
      Title: options.title,
      Author: options.author || 'BOQ AI',
      Subject: options.subtitle,
    },
  });

  doc.fontSize(20).font('Helvetica-Bold').text(options.title, { align: 'center' });
  doc.moveDown(0.5);

  if (options.subtitle) {
    doc.fontSize(12).font('Helvetica').text(options.subtitle, { align: 'center' });
  }
  doc.moveDown(1);

  doc
    .fontSize(8)
    .font('Helvetica-Oblique')
    .text(`Generated by BOQ AI on ${new Date().toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(1);

  doc.strokeColor('#cccccc').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(1);

  return doc;
}

export function addPdfSection(doc: PDFKit.PDFDocument, title: string, content: string[][]): void {
  doc.fontSize(14).font('Helvetica-Bold').text(title);
  doc.moveDown(0.5);

  const tableTop = doc.y;
  const colWidths = [40, 250, 60, 80, 80];
  const headers = ['#', 'Description', 'Unit', 'Quantity', 'Amount'];

  doc.fontSize(9).font('Helvetica-Bold');
  let xPos = 50;
  headers.forEach((header, i) => {
    doc.text(header, xPos, tableTop, { width: colWidths[i], align: 'left' });
    xPos += colWidths[i];
  });
  doc.moveDown(0.5);

  doc.strokeColor('#cccccc').lineWidth(0.5).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.3);

  doc.fontSize(8).font('Helvetica');
  content.forEach((row, rowIndex) => {
    if (doc.y > 720) {
      doc.addPage();
    }
    xPos = 50;
    const rowY = doc.y;
    row.forEach((cell, i) => {
      doc.text(cell, xPos, rowY, { width: colWidths[i], align: i === 0 ? 'center' : 'left' });
      xPos += colWidths[i];
    });
    doc.moveDown(0.5);
  });

  doc.moveDown(1);
}

export function addPdfSummary(doc: PDFKit.PDFDocument, label: string, value: string): void {
  doc.fontSize(10).font('Helvetica');
  doc.text(`${label}: `, { continued: true });
  doc.font('Helvetica-Bold').text(value);
  doc.moveDown(0.3);
}

export function addPdfFooter(doc: PDFKit.PDFDocument, disclaimer: string): void {
  doc.moveDown(2);
  doc.strokeColor('#cccccc').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.5);
  doc
    .fontSize(7)
    .font('Helvetica-Oblique')
    .fillColor('#666666')
    .text(disclaimer, 50, doc.y, { width: 495, align: 'center' });
}

export function streamPdf(doc: PDFKit.PDFDocument, res: Response, filename: string): void {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  doc.pipe(res);
  doc.end();
}
